# serverless.yml

service: cities

provider:
  name: aws
  runtime: go1.x

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  cities:
    handler: bin/cities
    events:
      - http:
          path: cities
          method: get
  states:
    handler: bin/states
    events:
      - http:
          path: states
          method: get

plugins:
  - serverless-finch
  - serverless-sam

custom:
  stageVars:
    dev:
      region: us-west-2
    prod:
      region: us-west-2
  client:
    # deploy like this: serverless client deploy --aws-profile cities --region us-west-2
    bucketName: cities-front # -${self:provider.stage}
    distributionFolder: public